# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_video_verified'),
        ('mturk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFrameTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_id', models.CharField(blank=True, max_length=64)),
                ('hit_group', models.CharField(blank=True, max_length=64)),
                ('worker_id', models.CharField(blank=True, max_length=64)),
                ('sandbox', models.BooleanField(default=True)),
                ('time', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fullvideotask',
            name='sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fullvideotask',
            name='worker_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
