# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0002_auto_20160814_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='assignment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='assignment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
