# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0003_auto_20160815_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='fullvideotask',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
