# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0004_auto_20160816_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='time_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='time_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
