# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0005_auto_20160816_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='metrics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='metrics',
            field=models.TextField(blank=True),
        ),
    ]
