# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0006_auto_20160821_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullvideotask',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singleframetask',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
