# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0007_auto_20161122_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fullvideotask',
            name='message',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='message',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
