# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0008_auto_20161127_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullvideotask',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='singleframetask',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
