# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0009_auto_20161128_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='email_trail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='email_trail',
            field=models.TextField(blank=True),
        ),
    ]
