# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0010_auto_20161129_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvideotask',
            name='last_email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singleframetask',
            name='last_email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
