# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0011_auto_20161129_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullvideotask',
            name='assignment_id',
            field=models.CharField(blank=True, help_text='ID of matching between this task and a worker. Used for authentication', max_length=64),
        ),
        migrations.AlterField(
            model_name='fullvideotask',
            name='hit_group',
            field=models.CharField(blank=True, help_text='Group ID on Mturk. HITs with same title/description usually are placed in the same group by MTurk. Auto-populated when publishing.', max_length=64),
        ),
        migrations.AlterField(
            model_name='fullvideotask',
            name='hit_id',
            field=models.CharField(blank=True, help_text='ID on MTurk. Auto-populated when publishing', max_length=64),
        ),
        migrations.AlterField(
            model_name='fullvideotask',
            name='worker_id',
            field=models.CharField(blank=True, help_text='ID of worker who submitted this HIT', max_length=64),
        ),
        migrations.AlterField(
            model_name='singleframetask',
            name='assignment_id',
            field=models.CharField(blank=True, help_text='ID of matching between this task and a worker. Used for authentication', max_length=64),
        ),
        migrations.AlterField(
            model_name='singleframetask',
            name='hit_group',
            field=models.CharField(blank=True, help_text='Group ID on Mturk. HITs with same title/description usually are placed in the same group by MTurk. Auto-populated when publishing.', max_length=64),
        ),
        migrations.AlterField(
            model_name='singleframetask',
            name='hit_id',
            field=models.CharField(blank=True, help_text='ID on MTurk. Auto-populated when publishing', max_length=64),
        ),
        migrations.AlterField(
            model_name='singleframetask',
            name='worker_id',
            field=models.CharField(blank=True, help_text='ID of worker who submitted this HIT', max_length=64),
        ),
    ]
