# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('annotation', models.TextField()),
            ],
        ),
    ]
