# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(default='', max_length=1048),
        ),
    ]
