# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
