# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20160720_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
