# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_video_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='annotation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(blank=True, max_length=1048),
        ),
    ]
