# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_video_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
