# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_video_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.RunSQL("INSERT INTO annotator_label (name, color) VALUES ('Car', 'd9534f');"),
        migrations.RunSQL("INSERT INTO annotator_label (name, color) VALUES ('Pedestrian', '337ab7');"),
        migrations.RunSQL("INSERT INTO annotator_label (name, color) VALUES ('Bicycle', '5cb85c');"),
        migrations.RunSQL("INSERT INTO annotator_label (name, color) VALUES ('Traffic Light', '5bc0de');"),
        migrations.RunSQL("INSERT INTO annotator_label (name, color) VALUES ('Pedestrian Signal', 'f0ad4e');"),
        migrations.RunSQL("INSERT INTO annotator_label (name, color) VALUES ('Crosswalk', '777777');"),
    ]
