# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_add_label_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_list',
            field=models.TextField(blank=True),
        ),
    ]
