# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_image_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
