# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20170417_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='labels',
            field=models.ManyToManyField(to='annotator.Label'),
        ),
    ]
