# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_video_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='labels',
            field=models.ManyToManyField(blank=True, to='annotator.Label'),
        ),
    ]
