# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20170815_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of class label option.', max_length=100)),
                ('color', models.CharField(blank=True, help_text='6 digit hex.', max_length=6)),
                ('label_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.Label', to_field='name')),
            ],
        ),
    ]
